baseURL: https://hbstack.dev/
title: HB Framework
copyright: "Copyright © 2022-{year} [HB Framework](https://hbstack.dev/). All Rights Reserved."
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
# disqusShortname: hbstack
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true

permalinks:
  blog: /blog/:year/:month/:title
  news: /news/:year/:month/:title

outputs:
  home:
    - HTML
    - Offline
    - RSS
    - SearchIndex
    - WebAppManifest
    - DecapCMSConfig

taxonomies:
  authors: authors
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true

related:
  threshold: 20
  indices:
    - name: categories
      type: basic
      weight: 80
    - name: tags
      type: basic
      weight: 80
    - name: series
      type: basic
      weight: 80

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
  tableOfContents:
    endLevel: 6
    startLevel: 2

security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^GITHUB_TOKEN$'

# ignoreErrors:
#   - error-remote-getjson

cascade:
  - _target:
      path: '*/**'
    params:
      authors:
        - HB
  - _target:
      path: /releases/*/**
      environment: development
    _build:
      list: never
      render: never
