google_adsense: ca-pub-7827859788508375

services:
  umami_analytics:
    id: ef4bea52-3cb7-40ca-abf7-a5441354cc9b
  microsoft_clarity:
    id: jqynhnhhg9w

decap_cms:
  backend:
    name: github
    repo: hbstack/site
    branch: main
    open_authoring: true

